spring:
  redis:
    host: 120.79.31.91
    port: 6379
    password: test123
    timeout: 5000
    database: 13
    jedis:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 0
        max-wait: 1000