spring:
  redis:
    host: 127.0.0.1
    port: 6379
    password: lzskroot
    timeout: 5000
    database: 11
    jedis:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 0
        max-wait: 1000