server:
  port: 27000
  tomcat:
    max-threads: 50
eureka:
  client:
    service-url:
      defaultZone: http://localhost:20000/eureka
spring:
  application:
    name: scfcloud-ticket

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

session:
  redis:
    keyPrefix: SHIRO-SESSION-MANAGER

mybatis-plus:
  mapper-locations: classpath*:com/zhjs/scfcloud/model/mapper/mapping/*.xml
#  type-aliases-package: classpath*:com.zhjs.scfcloud.model.entity
  type-enums-package: classpath*:com/zhjs/scfcloud/model/enums
  global-config:
    db-config:
      id-type: auto
      field-strategy: 0
      capital-mode: true
      table-underline: true
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

## 设置feign超时
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000