server:
  port: 21000
  tomcat:
    max-threads: 50
eureka:
  client:
    service-url:
      defaultZone: http://localhost:20000/eureka
      #eureka client刷新本地缓存时间
      #默认30s
      registry-fetch-interval-seconds: 5
spring:
  application:
    name: scfcloud
  #feign2.1.1版本需要设置此属性才可运行多个feign指定同一个服务名
  main:
    allow-bean-definition-overriding: true

  ## 时间格式化
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

session:
  redis:
    keyPrefix: SHIRO-SESSION-MANAGER

## 设置feign超时
feign:
  client:
    config:
      default:
        connectTimeout: 20000
        readTimeout: 20000
