server:
  port: 25000
  tomcat:
    max-threads: 20
eureka:
  client:
    service-url:
      defaultZone: http://localhost:20000/eureka
spring:
  application:
    name: scfcloud-task
  #feign2.1.1版本需要设置此属性才可运行多个feign指定同一个服务名
  main:
    allow-bean-definition-overriding: true
mybatis-plus:
  mapper-locations: classpath*:com/zhjs/scfcloud/model/mapper/mapping/*.xml
#  type-aliases-package: classpath*:com.zhjs.scfcloud.model.entity
  type-enums-package: classpath*:com/zhjs/scfcloud/model/enums
  global-config:
    db-config:
      id-type: auto
      field-strategy: 0
      capital-mode: true
      table-underline: true
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
