spring:
  redis:
    host: 172.18.232.179
    port: 6379
    password: test123
    timeout: 5000
    database: 6
    jedis:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 0
        max-wait: 1000