mail:
  host: smtp.exmail.qq.com
  port: 465
  protocol: smtp
  default-encoding: UTF-8

#\u53D1\u9001\u65B9\u7684\u90AE\u7BB1
  username: lingzhufin@zhihuikg.com
#\u5BF9\u4E8Eqq\u90AE\u7BB1\u800C\u8A00 \u5BC6\u7801\u6307\u7684\u5C31\u662F\u53D1\u9001\u65B9\u7684\u6388\u6743\u7801
  password: Kg123456

# \u8BBE\u7F6E\u662F\u5426\u9700\u8981\u8BA4\u8BC1\uFF0C\u5982\u679C\u4E3Atrue,\u90A3\u4E48\u7528\u6237\u540D\u548C\u5BC6\u7801\u5C31\u5FC5\u987B\u7684\uFF0C
# \u5982\u679C\u8BBE\u7F6Efalse\uFF0C\u53EF\u4EE5\u4E0D\u8BBE\u7F6E\u7528\u6237\u540D\u548C\u5BC6\u7801\uFF0C\u5F53\u7136\u4E5F\u5F97\u770B\u4F60\u7684\u5BF9\u63A5\u7684\u5E73\u53F0\u662F\u5426\u652F\u6301\u65E0\u5BC6\u7801\u8FDB\u884C\u8BBF\u95EE\u7684\u3002
  smtp:
    auth: true
# STARTTLS[1]  \u662F\u5BF9\u7EAF\u6587\u672C\u901A\u4FE1\u534F\u8BAE\u7684\u6269\u5C55\u3002\u5B83\u63D0\u4F9B\u4E00\u79CD\u65B9\u5F0F\u5C06\u7EAF\u6587\u672C\u8FDE\u63A5\u5347\u7EA7\u4E3A\u52A0\u5BC6\u8FDE\u63A5\uFF08TLS\u6216SSL\uFF09\uFF0C\u800C\u4E0D\u662F\u53E6\u5916\u4F7F\u7528\u4E00\u4E2A\u7AEF\u53E3\u4F5C\u52A0\u5BC6\u901A\u4FE1\u3002
    starttls:
       enable: true
       required: true
# \u4F01\u4E1A\u90AE\u7BB1\u51FA\u4E8E\u5B89\u5168\u6027\u8003\u8651\uFF0C\u670D\u52A1\u5668\u8981\u6C42\u5FC5\u987B\u8981\u4F7F\u7528 SSL \u5B89\u5168\u8FDE\u63A5
    ssl:
      enable: true
# 开启DEBUG模式
  debug: true

##\u9886\u7B51\u4E91\u77ED\u4FE1\u63A5\u53E3\u5730\u5740
lzCloudSmsUrl: http://localhost:7003/lz/sms/bsend

## 文件服务器地址
file:
  service:
    url: http://www.lingzhufin.com/scfcloud-file/

## 接收京东智票异步回调地址
jdzp:
  platform:
    return:
      url: http://www.lingzhufin.com/scfcloud-ticket/platform/jdzpNotify

file-upload-url: http://www.lingzhufin.com/scfcloud-file/file/upload #文件服务器上传地址

## 领筑互联电签相关配置
hulian-esign:
  appId: e21210cdac2011e98b24408d5c99f2ad
  contract-template-path: /app/file/contract/template.pdf  #合同模板路径
  url: https://api.lingzhuyun.com/esign-service/ #领筑互联电签服务地址
  sign:
    create-person: signAcc/createPerson
    create-organize: signAcc/createOrganize
    add-person-seal: signAcc/addPersonSeal
    add-organize-seal: signAcc/addOrganizeSeal
    send-sms-code: sign/sendSmsCode
    sign-mobile-a1: sign/userStreamMobileSignA1
    sign-mobile-a2: sign/userStreamMobileSignA2
    sign-mobile-b1: sign/userStreamMobileSignB1
    sign-mobile-b2: sign/userStreamMobileSignB2
  file:
    upload: file/fileUpload
    download: file/fileDownload
    tmp-pdf-path: /app/file/temp/tmp.pdf  #本机存放临时合同文件路径

## 领筑云短信-邮件-天眼查   服务配置
lingzhuyun:
  # 请求的渠道编码，类似appkey，由服务提供者分配
  bizChannel: a6d42ceb4e3e40e084b14a7864605da3
  # 请求的秘钥，类似appSecret，由服务提供者分配
  bizSecret: a818e99586ea97be711b803b42fd5663
  # 领筑云URL
  smsUrl: https://api.lingzhuyun.com

# 指定本地配置文件目录
local:
  config:
    active: pro

#api接口 合作方ids 多个逗号隔开
api:
  partnerIds: 1

##前端路由URL
frontEndUrl:
  risk: http://www.lingzhufin.com/risk
  bill: http://www.lingzhufin.com/bill

##短信发送开关配置(0:关 1:开)
smsSendSwitch: 1
